---
title: "R Project"
author: "Hannah Li"
date: "8/12/2019"
output: html_document
---
Cleaning Data
```{r}
library(ISLR)
setwd("C:/Users/hanna/OneDrive/Desktop/MSBA/PM/Project")
raw_data = read.csv('data.csv')
n = dim(raw_data)[1]

library(DataExplorer)
library(ggplot2)
str(raw_data)

raw_data$date_clean <- substr(raw_data$date, 0, 19)
raw_data$date_new <- substr(raw_data$date, 0, 14)
raw_data$date_new_half <- substr(raw_data$date, 15, 15)
raw_data$data_new_half <- as.numeric(raw_data$date_new_half)
raw_data$minutes_hour <- ifelse(raw_data$data_new_half <= 3,'00:00', '30:00')
raw_data$time_clean <- paste( raw_data$date_new, raw_data$minutes_hour,sep='') 
raw_data$date_object <- strptime(as.character(raw_data$time_clean), "%Y-%m-%d %H:%M:%S")
raw_data$day_of_wk <- weekdays(raw_data$date_object)
raw_data$month_txt <- months(raw_data$date_object)

library(data.table)
setDT(raw_data)

raw_data$is_holiday <- as.numeric(raw_data$is_holiday)
raw_data$is_weekend <- as.numeric(raw_data$is_weekend)
raw_data$is_during_semester <- as.numeric(raw_data$is_during_semester)
raw_data$is_start_of_semester <- as.numeric(raw_data$is_start_of_semester)

str(raw_data)
new_data <- as.data.frame(raw_data[,list(temperature=mean(temperature),
                                         num_people= mean(number_people),
                                         is_holiday = mean(is_holiday),
                                         is_weekend = mean(is_weekend),
                                         is_start_of_semester =mean(is_start_of_semester),
                                         is_during_semester = mean(is_during_semester)), by=list(time_clean)])
new_data$date_object <- strptime(as.character(new_data$time_clean), "%Y-%m-%d %H:%M:%S")

new_data$day_of_wk <- weekdays(new_data$date_object)
new_data$month_txt <- months(new_data$date_object)
new_data$hour_of_the_day <- hour(new_data$date_object)

start <- as.POSIXct("2015-08-14")
interval <- 30

end <- start + as.difftime(583, units="days")

dates<-seq(from=start, by=interval*60, to=end)

fresh_data <- data.frame(dates, '0')
fresh_data$time_clean <- fresh_data$dates
fresh_data$time_clean <- as.character(fresh_data$time_clean)
fresh_data_new<- merge(x =fresh_data, y =new_data, by = "time_clean", all.x = TRUE)

fresh_data_new[1,c('is_holiday')] <- 0
fresh_data_new[1,c('is_weekend')] <- 0
fresh_data_new[1,c('is_start_of_semester')] <- 0
fresh_data_new[1,c('is_during_semester')] <- 0
fresh_data_new[1,c('num_people')] <- 0
fresh_data_new[1,c('temperature')] <- 71.760

library(zoo)
fresh_data_new$temperature <- (na.locf(fresh_data_new$temperature) + rev(na.locf(rev(fresh_data_new$temperature))))/2

fresh_data_new$num_people <- ifelse(is.na(fresh_data_new$num_people),0,
                                    fresh_data_new$num_people)
fresh_data_new$is_holiday <- (na.locf(fresh_data_new$is_holiday) + rev(na.locf(rev(fresh_data_new$is_holiday))))/2
fresh_data_new$is_weekend <- (na.locf(fresh_data_new$is_weekend) + rev(na.locf(rev(fresh_data_new$is_weekend))))/2

fresh_data_new$is_start_of_semester <- (na.locf(fresh_data_new$is_start_of_semester) + rev(na.locf(rev(fresh_data_new$is_start_of_semester))))/2


fresh_data_new$is_during_semester <- (na.locf(fresh_data_new$is_during_semester) + rev(na.locf(rev(fresh_data_new$is_during_semester))))/2

fresh_data_new$date_object <- NULL
fresh_data_new$day_of_wk <- NULL
fresh_data_new$month_txt <- NULL
fresh_data_new$hour_of_the_day <- NULL
fresh_data_new$X.0. <- NULL

str(fresh_data_new)

fresh_data_new$day_of_wk <- weekdays(fresh_data_new$dates)
fresh_data_new$month <- months(fresh_data_new$dates)
fresh_data_new$hour_of_day <- hour(fresh_data_new$dates)

library(DataCombine)

fresh_data_new <- slide(fresh_data_new, Var = "num_people", slideBy = -48)
fresh_data_new$lag_1_day <- fresh_data_new$`num_people-48`

fresh_data_new <- fresh_data_new[-c(27985),]
fresh_data_new <- slide(fresh_data_new, Var = "num_people", slideBy = -336)
fresh_data_new$lag_1_week <- fresh_data_new$`num_people-336`

fresh_data_new$`num_people-48` <- NULL 
fresh_data_new$`num_people-336` <- NULL

fresh_data_new$lag_1_day <- ifelse(is.na(fresh_data_new$lag_1_day), 0,
                                   fresh_data_new$lag_1_day)
fresh_data_new$lag_1_week <- ifelse(is.na(fresh_data_new$lag_1_week), 0,
                                    fresh_data_new$lag_1_week)

fresh_data_new<- fresh_data_new[order(fresh_data_new$dates),]

library(chron)
library(timeDate)

#making a list of holidays
hlist <- c("USChristmasDay","USGoodFriday","USIndependenceDay","USLaborDay",
           "USNewYearsDay","USThanksgivingDay")        
myholidays  <- dates(as.character(holiday(2015:2018,hlist)),format="Y-M-D")

fresh_data_new$public_holiday <-is.holiday(fresh_data_new$dates,myholidays)

fresh_data_new$is_weekend <- ifelse(fresh_data_new$is_weekend > 0.6, 1,0)
fresh_data_new$is_holiday <- ifelse(fresh_data_new$is_holiday > 0.6, 1,0)
fresh_data_new$is_during_semester <- ifelse(fresh_data_new$is_during_semester > 0.6, 1,0)
fresh_data_new$is_start_of_semester <- ifelse(fresh_data_new$is_start_of_semester > 0.6, 1,0)

library(fastDummies)
str(fresh_data_new)
fresh_data_new$is_start_of_semester <-factor(fresh_data_new$is_start_of_semester)
fresh_data_new$is_during_semester <- factor(fresh_data_new$is_during_semester)
fresh_data_new$day_of_wk <- factor(fresh_data_new$day_of_wk )
fresh_data_new$is_weekend  <- factor(fresh_data_new$is_weekend )
fresh_data_new$month <- factor(fresh_data_new$month)
fresh_data_new$hour_of_day <- factor(fresh_data_new$hour_of_day)
fresh_data_new$is_holiday <- factor(fresh_data_new$is_holiday)
fresh_data_new$public_holiday <- factor(fresh_data_new$public_holiday)

str(fresh_data_new)

features <- names(fresh_data_new)[3:14]
features <- features[features != "is_holiday"]
#creating train and test set
train <- fresh_data_new[1:22368,features]
test <- fresh_data_new[22369:nrow(fresh_data_new),features]

#write new train/test.csv to csv files
write.csv(train, 'train_final.csv', row.names=FALSE)
write.csv(test, 'test_final.csv',row.names=FALSE)

#testing with simple mean model
mean_model <- mean(train$num_people)
sqrt(mean(mean_model - test$num_people)^2)
#RMSE = 19.99802 for mean model
```
Multiple Linear Regression
```{r}
lm.fit <- lm(num_people~., data = train)
summary(lm.fit)
#plot(lm.fit)

y_test <- test$num_people
#need to take out num_people before doing prediction bc it is the response variable
test$num_people <- NULL

predictions_lm <- predict(lm.fit, test)
#predictions_lm
#run the line above and WE SEE IT PRODUCES NEGATIVE PREDICTED VALUES. We cannot have negative number of people at the gym so we must use a different distribution.
rmse = sqrt(mean(predictions_lm - y_test)^2)
rmse
#RMSE for MLR (no interaction) is 3.196

plot(predictions_lm, y_test,
     xlab="predicted",ylab="actual", title("MLR"))
abline(0,1, col = 'red')
```

Negative Binomial
```{r, warning=FALSE}
library(MASS)
set.seed(123)
test <- fresh_data_new[22369:nrow(fresh_data_new),features]
y_test <- test$num_people
#need to take out num_people before doing prediction bc it is the response variable
test$num_people <- NULL

nb.fit = glm.nb(num_people~., data = train)
summary(nb.fit)

predictions_nb <- predict(nb.fit, test, type = 'response')
#run the above line to see that we get only positive response values
rmse_nb = sqrt(mean(predictions_nb - y_test)^2)
rmse_nb
#RMSE = 6.70225

#plot(nb.fit)
plot(predictions_nb, y_test,
     xlab="predicted",ylab="actual", title("Negative Binomial"))
abline(0,1, col = 'red')
```

Best Subset Selection
```{r}
library(leaps)
test <- fresh_data_new[22369:nrow(fresh_data_new),features]
y_test <- test$num_people

regfit.best = regsubsets(num_people~., train, nvmax = 10)
test.mat = model.matrix(num_people~., test)
val.errors = rep(NA, 10)
for (i in 1:10){
  gym_coefi = coef(regfit.best, id = i)
  pred = test.mat[,names(gym_coefi)]%*%gym_coefi
  val.errors[i]=mean((y_test-pred)^2)
}
val.errors
which.min(val.errors)
coef(regfit.best,6)
```
We get the best 6 predictors to be 1 Week Lag, Start of Semester: True, Public Holiday: True, Day of Week: Monday, Day of Week: Saturday, 1 Day Lag

Best Subset for MLR
```{r}
lm.bestsub = lm(num_people~+lag_1_week+is_start_of_semester+public_holiday+day_of_wk+lag_1_day, data = train)
summary(lm.bestsub)
predictions_lm_best <- predict(lm.bestsub, test, type = 'response')
#predictions_lm_best
rmse_lm = sqrt(mean(predictions_lm_best - y_test)^2)
rmse_lm

plot(predictions_lm_best, y_test,
     xlab="predicted",ylab="actual", title("MLR (Best Subset)"))
abline(0,1, col = 'red')
```

Best Subset for Negative Binomial
```{r, warning=FALSE}
#Best subset for NB with the 6 predictors
nb.bestsub = glm.nb(num_people~+lag_1_week+is_start_of_semester+public_holiday+day_of_wk+lag_1_day, data = train)
#summary(nb.bestsub)
predictions_nb_best <- predict(nb.bestsub, test, type = 'response')
#predictions_nb_best
rmse_nb = sqrt(mean(predictions_nb_best - y_test)^2)
rmse_nb
#rmse of 4.914 after doing best subset on these 6 predictors.

plot(predictions_nb_best, y_test,
     xlab="predicted",ylab="actual", title("Negative Binomial (Best Subset)"))
abline(0,1, col = 'red')
```
